name: CI Pipeline for Kotlin App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Java environment
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'  # Use 'temurin' instead of 'adoptopenjdk'

      # Step 3: Set execute permissions for gradlew
      - name: Set execute permissions for gradlew
        run: chmod +x gradlew

      # Step 4: Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: Linux-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            Linux-gradle-


     
   # Step 5: Install dependencies
      - name: Install Dependencies
        run: ./gradlew dependencies

      # Step 6: Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Step 7: Build APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # Step 8: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Step 9: Run Detekt (Static Code Analysis)
      - name: Run Detekt
        run: ./gradlew detekt

      # Step 10: Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      # Step 11: Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

